@echo off
echo Downloading MUSCLE...
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/rcedgar/muscle/releases/download/5.1.0/muscle5.1.win64.exe', '%cd%\muscle5.1.win64.exe')"
echo Creating bin directory...
mkdir bin
echo Copying MUSCLE to bin directory...
copy muscle5.1.win64.exe .\bin\muscle.exe
echo Testing MUSCLE installation...
bin\muscle.exe"
pause
###