@echo off
echo Downloading MUSCLE...
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/rcedgar/muscle/releases/download/5.1.0/muscle5.1.win64.exe', '%cd%\muscle5.1.win64.exe')"
echo Creating bin directory...
mkdir bin
echo Renaming MUSCLE executable...
move muscle5.1.win64.exe muscle.exe
echo Testing MUSCLE installation...
muscle.exe -h
pause
